#' SESplot
#' 
#' To draw relevant chart of a ses object. Includes bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' Available isobaths range from -200 to -4400 meters by 200 m.
#' 
#' @param ses An ses object (generated by importSES).
#' @inheritParams SESplot.ses
#' @param ... Other parameters to be passed to methods.
#' @import maptools fields maps 
#' @family SESplot
#' @export
#' @examples
#' \dontrun{
#' require(maps)
#' path <- system.file("extdata", package="SES")
#' pathname <- file.path(path, "2011-16_SES_example_accelero.mat")
#' ses <- importSES(pathname)
#' SESplot(ses, isobath=-1000, colorvar=ses$stat$Catch.numb)
#' library("RColorBrewer")
#' mycol <- brewer.pal(n=10, name="BrBG")
#' SESplot(ses, ses$stat$Dive.dur, pts.args=list(pch=""), implt.args=list(col=mycol), img.args=list(nx=150, ny=150))
#' }
SESplot <- function(ses, colorvar=NULL, isobath=NULL, ...){
	UseMethod("SESplot")
}

#' SESplot.ses
#' 
#' A S3 method for \code{SESplot()} with regular ses objects. Includes 
#' bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' 
#' @param ses An ses object (generated by importSES).
#' @param colorvar A 'statdives' variable to plot along the trajectory.
#' @param isobath Isobaths to draw. Default is NULL (none). 
#' Isobath at -1000 m corresponds approximatively to the Kerguelen shell 
#' boarder. Slow down the function (shapefile loading). Available isobaths range
#'  from -200 to -4400 meters by 200 m.
#' @param pts.args Other parameters to be passed to \code{\link{points}}. 
#' Defaults: \code{list(pch=19, cex=.1)}.
#' @param map.args Other parameters to be passed to \code{\link{map}}. 
#' Defaults: \code{list(fill=TRUE, col="gray")}.
#' @param img.args Other parameters to be passed to \code{\link{as.image}}.
#' Notice the possibility to set \code{nx} and \code{ny} arguments.
#' @param implt.args Other parameters to be passed to \code{\link{image.plot}}.
#' Defaults: \code{list(legend.width=1, legend.mar=7.8, legend.shrink=.7, 
#' legend.lab=deparse(substitute(colorvar)), legend.line=3.5)} with 
#' \code{par(mar=c(4.2,4.2,3.5,7.9))}. Notice the possibility to set \code{zlim}, 
#' \code{col}, \code{breaks} arguments.
#' @details If this error show up 'data set ‘worldMapEnv’ not found' 
#' try \code{require(maps)}. See examples in \code{\link{SESplot}}.
#' @family SESplot
#' @import maptools fields maps
#' @method SESplot ses
#' @export
SESplot.ses <- function(ses, colorvar=NULL, isobath=NULL, pts.args=list(), 
						map.args=list(), img.args=list(), implt.args=list()) {
	findVars(c("Ind.id", "stat"), ses)
	findDefaultVars(c("Lat", "Lon", "Time"), stat, type.obj="stat")
	# Settings
	opar <- par("mar") ; on.exit(par(opar))
	par(mar=c(4.2,4.2,3.5,7.9))
	defaults <- list(pts.args=list(pch=19, cex=.1), map.args=list(fill=TRUE, col="gray"), 
					 img.args=list(),
					 implt.args=list(legend.width=1, legend.mar=7.8, legend.shrink=.7,
					 			   legend.lab=deparse(substitute(colorvar)), legend.line=3.5))
	chkArgs <- function(args, def) c(args, def[!names(def) %in% names(args)])
	for (i in seq_along(defaults)) {
		assign(names(defaults)[i], chkArgs(get(names(defaults)[i]), defaults[[i]]))
	}
	# Call plot functions
	plot(Lat ~ Lon, type="n")
	if (!is.null(colorvar)) {
		im <- do.call('as.image', c(list(colorvar, x=data.frame(Lon, Lat)), img.args))
		do.call('image.plot', c(list(im, add=TRUE), implt.args))
	}
	do.call('points', c(list(Lat ~ Lon), pts.args))
	title(main=paste(Ind.id, ": ", nrow(stat), "dives"), line=2)
	mtext(text=paste(range(Time), collapse="  -->  "), side=3, line=.75)
	points(Lat ~ Lon, data=stat[1, ], col="deeppink3", pch="*", cex=3)
	do.call('map', c(list(add=TRUE), map.args))
	if (!is.null(isobath)) {
		bath <- readShapeSpatial(file.path(system.file("extdata", package="SES"), "bath.shp"))
		bath <- bath[bath$CONTOUR %in% isobath, ]
		lines(bath, lty=2)
	}
}

# #' SESplot.tdr3D
# #' 
# #'  A method for \code{SESplot()} with tdr3D objects.
# #'  
# #' @inheritParams SESplot.ses
# #' @param ... Other parameters to be passed to \code{scatterplot3d()} or \code{par()}.
# #' @family SESplot
# # @import scatterplot3d
# #' @S3method SESplot tdr3D
# SESplot.tdr3D <- function(ses, pch=19, cex=1,
# 						  Z=NULL, Z.col=tim.colors(64), ...){
# }
