#' SESplot
#' 
#' To draw relevant chart of a ses object. Includes bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' Available isobaths range from -200 to -4400 meters by 200 m.
#' 
#' @param obj An ses object (generated by importSES).
#' @inheritParams SESplot.ses
#' @param ... Other parameters to be passed to methods.
#' @import maptools fields maps 
#' @family SESplot
#' @export
#' @examples
#' \dontrun{
#' require(maps)
#' path <- system.file("extdata", package="SES")
#' pathname <- file.path(path, "2011-16_SES_example_accelero.mat")
#' ses <- importSES(pathname)
#' SESplot(ses, isobath=-1000, colorvar=ses$stat$Catch.numb)
#' library("RColorBrewer")
#' mycol <- brewer.pal(n=10, name="BrBG")
#' SESplot(ses, ses$stat$Dive.dur, pts.args=list(pch=""), implt.args=list(col=mycol), img.args=list(nx=150, ny=150))
#' }
SESplot <- function(obj, colorvar=NULL, isobath=NULL, ...){
	UseMethod("SESplot")
}

#' SESplot.ses
#' 
#' A S3 method for \code{SESplot()} with regular ses objects. Includes 
#' bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' 
#' @param obj An ses object (generated by importSES).
#' @param colorvar A 'statdives' variable to plot along the trajectory.
#' @param cond A logical vector giving how to subset the rows of 
#' the 'statdives' object.
#' @param isobath Isobaths to draw. Default is NULL (none). 
#' Isobath at -1000 m corresponds approximatively to the Kerguelen shell 
#' boarder. Slow down the function (shapefile loading). Available isobaths range 
#' from -200 to -4400 meters by 200 m.
#' @param pts.args Other parameters to be passed to \code{\link{points}}. 
#' Defaults: \code{list(pch=19, cex=.1)}.
#' @param map.args Other parameters to be passed to \code{\link{map}}. 
#' Defaults: \code{list(fill=TRUE, col="gray")}.
#' @param img.args Other parameters to be passed to \code{\link{as.image}}.
#' Notice the possibility to set \code{nx} and \code{ny} arguments.
#' @param implt.args Other parameters to be passed to \code{\link{image.plot}}.
#' Defaults: \code{list(legend.width=1, legend.mar=7.8, legend.shrink=.7, 
#' legend.lab=deparse(substitute(colorvar)), legend.line=3.5)} with 
#' \code{par(mar=c(4.2,4.2,3.5,7.9))}. Notice the possibility to set \code{zlim}, 
#' \code{col}, \code{breaks} arguments.
#' @param plt.args Other parameters to be passed to \code{\link{plot}}.
#' Notice the possibility to set \code{xlim} and \code{ylim} arguments.
#' @details If this error show up 'data set ‘worldMapEnv’ not found' 
#' try \code{require(maps)}. See examples in \code{\link{SESplot}}.
#' @family SESplot
#' @import maptools fields maps
#' @method SESplot ses
#' @export
SESplot.ses <- function(obj, colorvar=NULL, cond=NULL, isobath=NULL, pts.args=list(), 
						map.args=list(), img.args=list(), implt.args=list(), plt.args=list()) {
	findVars(c("Ind.id", "stat"), obj)
	SESplot.statdives(stat, colorvar, cond, isobath, pts.args, 
					  map.args, img.args, implt.args, plt.args, 
					  colorvarname=deparse(substitute(colorvar)))
	title(main=paste(Ind.id, ": ", nrow(stat), "dives"), line=2)
}

#' SESplot.statdives
#' 
#' A S3 method for \code{SESplot()} with regular ses objects. Includes 
#' bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' 
#' @param obj An ses object (generated by importSES).
#' @param colorvar A 'statdives' variable to plot along the trajectory.
#' @param cond A logical vector giving how to subset the rows of 
#' the 'statdives' object.
#' @param isobath Isobaths to draw. Default is NULL (none). 
#' Isobath at -1000 m corresponds approximatively to the Kerguelen shell 
#' boarder. Slow down the function (shapefile loading). Available isobaths range 
#' from -200 to -4400 meters by 200 m.
#' @param pts.args Other parameters to be passed to \code{\link{points}}. 
#' Defaults: \code{list(pch=19, cex=.1)}.
#' @param map.args Other parameters to be passed to \code{\link{map}}. 
#' Defaults: \code{list(fill=TRUE, col="gray")}.
#' @param img.args Other parameters to be passed to \code{\link{as.image}}.
#' Notice the possibility to set \code{nx} and \code{ny} arguments.
#' @param implt.args Other parameters to be passed to \code{\link{image.plot}}.
#' Defaults: \code{list(legend.width=1, legend.mar=7.8, legend.shrink=.7, 
#' legend.lab=deparse(substitute(colorvar)), legend.line=3.5)} with 
#' \code{par(mar=c(4.2,4.2,3.5,7.9))}. Notice the possibility to set \code{zlim}, 
#' \code{col}, \code{breaks} arguments.
#' @param plt.args Other parameters to be passed to \code{\link{plot}}.
#' Notice the possibility to set \code{xlim} and \code{ylim} arguments.
#' @param colorvarname Name for the legend. For compatibility when called from 
#' \code{SESplot.ses()}
#' @details If this error show up 'data set ‘worldMapEnv’ not found' 
#' try \code{require(maps)}. See examples in \code{\link{SESplot}}.
#' @family SESplot
#' @import maptools fields maps
#' @method SESplot ses
#' @export
SESplot.statdives <- function(obj, colorvar=NULL, cond=NULL, isobath=NULL, pts.args=list(), 
						map.args=list(), img.args=list(), implt.args=list(), plt.args=list(),
							  colorvarname) {
	if (missing(colorvarname)) colorvarname <- deparse(substitute(colorvar))
	nas <- apply(is.na(obj), 1, any)
	obj <- obj[!nas, ] ; colorvar <- colorvar[!nas]
	if (!is.null(cond)){
		obj <- obj[cond & !nas, ]
		colorvar <- colorvar[cond]
	}
	if (inherits(obj, "statdives3D")) {
		findVars(c("Lat.i", "Lon.i", "Dive.id"), obj, varnames=c("Lat", "Lon", "Time"))
	} else {
		findDefaultVars(c("Lat", "Lon", "Time"), obj, type.obj="stat", substring=FALSE)
	}
	# Settings
	opar <- par("mar") ; on.exit(par(opar))
	par(mar=c(4.2,4.2,3.5,7.9))
	defaults <- list(pts.args=list(pch=19, cex=.1), map.args=list(fill=TRUE, col="gray"), 
					 img.args=list(na.rm=TRUE),
					 implt.args=list(legend.width=1, legend.mar=7.8, legend.shrink=.7,
					 				legend.lab=colorvarname, legend.line=3.5),
					 plt.args=list())
	chkArgs <- function(args, def) c(args, def[!names(def) %in% names(args)])
	for (i in seq_along(defaults)) {
		assign(names(defaults)[i], chkArgs(get(names(defaults)[i]), defaults[[i]]))
	}
	# Call plot functions
	do.call('plot', c(list(Lat ~ Lon, type="n"), plt.args))
	if (!is.null(colorvar)) {
		im <- do.call('as.image', c(list(colorvar, x=data.frame(Lon, Lat)), img.args))
		do.call('image.plot', c(list(im, add=TRUE), implt.args))
	}
	do.call('points', c(list(Lat ~ Lon), pts.args))
	mtext(text=paste(range(Time), collapse="  -->  "), side=3, line=.75)
	points(Lon[1], Lat[1], col="deeppink3", pch="*", cex=3)
	do.call('map', c(list(add=TRUE), map.args))
	if (!is.null(isobath)) {
		bath <- readShapeSpatial(file.path(system.file("extdata", package="SES"), "bath.shp"))
		bath <- bath[bath$CONTOUR %in% isobath, ]
		lines(bath, lty=2)
	}
}

#' SESplot.tdr3D
#' 
#'  A method for \code{SESplot()} with tdr3D objects.
#'  
#' @inheritParams SESplot.ses
#' @param scatter.args Other parameters to be passed to \code{scatterplot3d}. 
#' Defaults: \code{list(pch=19, cex.symbol=.1, mar=c(4.2,4.2,3.5,9)))}
#' @param colscale.args Other parameters to be passed to \code{\link{color.scale}}. 
#' Defaults: \code{list()}.
#' @param implt.args Other parameters to be passed to \code{\link{image.plot}}. 
#' Defaults: \code{list(side=3, legend.width=1, legend.mar=7.8, legend.shrink=.7, 
#' legend.lab=colorvarname, legend.line=3.5)}.
#' @family SESplot
#' @import fields
#' @S3method SESplot tdr3D
SESplot.tdr3D <- function(obj, colorvar=NULL, cond=NULL, isobath=NULL,
						  scatter.args=list(), colscale.args=list(), implt.args=list()){
	colorvarname <- deparse(substitute(colorvar))
	if (!is.null(cond)) {
		obj <- obj[cond, ]
		colorvar <- colorvar[cond]
	}
	findDefaultVars(c("Lat", "Lon", "Time", "Depth"), obj, type.obj="tdr3D")
	# Settings
	defaults <- list(scatter.args=list(pch=19, cex.symbol=.1, mar=c(4.2,4.2,3.5,9)), 
					 colscale.args=list(),
					 implt.args=list(side=3, legend.width=1, legend.mar=7.8, legend.shrink=.7,
					 				legend.lab=colorvarname, legend.line=3.5))
	chkArgs <- function(args, def) c(args, def[!names(def) %in% names(args)])
	for (i in seq_along(defaults)) {
		assign(names(defaults)[i], chkArgs(get(names(defaults)[i]), defaults[[i]]))
	}
	# Colors
	if (!is.null(colorvar)){
		if (is.numeric(colorvar)){
			cols <- do.call('color.scale', c(list(z=colorvar), colscale.args))
		} else if (is.logical(colorvar)){
			cols <- cols + 1
		}
	} else {
		cols <- rep(1, length(Depth))
	}
	# Plot
	sp3 <- do.call(getFromNamespace('scatterplot3d', 'scatterplot3d'), c(list(Lon, Lat, Depth, color=cols, add=TRUE,
										   xlab="Lon", ylab="Lat", zlab="Depth"), scatter.args))
	sp3$points3d(Lon[1], Lat[1], Depth[1], col="deeppink3",
				 pch="*", cex=3)
	if (!is.null(isobath)) {for (iso in isobath) {sp3$plane3d(iso, 0, 0)}}
	if (!is.null(colorvar) & is.numeric(colorvar)) {
		do.call('image.plot', c(list(legend.only=TRUE, add=TRUE,
									 z=colorvar, col=cols), implt.args))
	}
}
