#' SESplot
#' 
#' To draw relevant chart of a ses object. Includes bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' Available isobaths range from -200 to -4400 meters by 200 m.
#' 
#' @param ses An ses object (generated by importSES).
#' @param ... Other parameters to be passed to methods.
#' @import maptools fields maps
#' @family SESplot
#' @export
#' @examples
#' \dontrun{
#' path <- system.file("extdata", package="SES")
#' pathname <- file.path(path, "2011-16_SES_example_accelero.mat")
#' ses <- importSES(pathname)
#' SESplot(ses, isobath=-1000, Z=ses$stat$Catch.numb)
#' library("RColorBrewer")
#' mycol <- brewer.pal(n=10, name="BrBG")
#' SESplot(ses, Z=ses$stat$Dive.dur, Z.col=mycol)
#' }
SESplot <- function(ses, ...){
	UseMethod("SESplot")
}

#' SESplot.ses
#' 
#' A S3 method for \code{SESplot()} with regular ses objects. Includes bathymetry taken from 
#' \url{https://www.ga.gov.au/products/servlet/controller?event=GEOCAT_DETAILS&catno=71552}. 
#' Available isobaths range from -200 to -4400 meters by 200 m.
#' 
#' @param ses An ses object (generated by importSES).
#' @param pch Plotting character.
#' @param cex Plotting character size.
#' @param fill Should the terrestrial area be filled with color.
#' @param m.col The color to use in order to fill the terrestrial area.
#' @param isobath Isobaths to draw. Default is NULL (none). Isobath at -1000 m corresponds 
#' approximatively to the Kerguelen shell boarder. Slow down the function (shapefile loading).
#' @param Z A 'statdives' variable to plot along the trajectory.
#' @param Z.col Colors for Z values.
#' @param ... Other parameters to be passed to \code{plot()} or \code{par()}.
#' @family SESplot
#' @import maptools fields maps
#' @method SESplot ses
#' @export
SESplot.ses <- function(ses, pch=19, cex=1, fill=TRUE,
						m.col="gray", isobath=NULL, 
						Z=NULL, Z.col=tim.colors(64), ...){
	
	old.par <- par("mar") ; on.exit(par(old.par))
	par(mar=c(4,4,3.5,6))
	findVars(c("Ind.id", "stat"), ses)
	statVars <- userHeader(c("Lat", "Lon", "Time"), type="stat")
	findVars(statVars, stat)
	plot(Lat ~ Lon, pch=pch, cex=cex*0.3, type="n")
	if (!is.null(Z)){
		im <- as.image(Z, x=data.frame(Lon, Lat))
		image.plot(im, add=TRUE, col=Z.col)
	}
	points(Lat ~ Lon, pch=pch, cex=cex*0.3, ...)
	title(main=paste(Ind.id, ": ", nrow(stat), "dives"), line=2)
	mtext(text=paste(range(Time), collapse="  -->  "), side=3, line=.75)
	points(Lat ~ Lon, data=stat[1, ], col="deeppink3", pch="*", cex=4)
# 	require(maps) # needed in dev mode
	map(add=TRUE, fill=fill, col=m.col)
	if (!is.null(isobath)){
		bath <- readShapeSpatial(file.path(system.file("extdata", package="SES"), "bath.shp"))
		bath <- bath[bath$CONTOUR %in% isobath, ]
		lines(bath, lty=2)
	}
}

# #' SESplot.tdr3D
# #' 
# #'  A method for \code{SESplot()} with tdr3D objects.
# #'  
# #' @inheritParams SESplot.ses
# #' @param ... Other parameters to be passed to \code{scatterplot3d()} or \code{par()}.
# #' @family SESplot
# # @import scatterplot3d
# #' @S3method SESplot tdr3D
# SESplot.tdr3D <- function(ses, pch=19, cex=1,
# 						  Z=NULL, Z.col=tim.colors(64), ...){
# }
