#' is.error
#' 
#' Test if 'x' is an error generated by \code{try()}.
#' 
#' @param x The object to test.
#' @export
#' @keywords internal
is.error <- function(x) {inherits(x, "try-error")}

#' %wo%
#' 
#' Returns values of 'x' cleaned from existing values of 'y' in 'x'.
#' 
#' @details %wo% = 'without' is equivalent to \code{setdiff}. Asymetric operation.
#' @export
#' @keywords internal
"%wo%" <- function(x, y) {x[!x %in% y]}

#' %wi%
#' 
#' Returns values of 'x' existing in 'y'.
#' 
#' @details %wi% = 'within' is equivalent to \code{intersect}. Symetric operation.
#' @export
#' @keywords internal
"%wi%" <- function(x, y){x[x %in% y]}

#' SESname
#' 
#' Extract the ID of an individual from a string that contains it.
#' 
#' @param text Text containing the seal ID.
#' @return TheiID as character
#' @family generalUtils
#' @export
#' @examples 
#' SESname("Path/to/seal/file/2011-12_some_ses_file.txt")
SESname <- function(text){regmatches(text, regexpr('20+[0-9]{2}-[0-9]{2}', text))}

#' replaceMissing
#' 
#' Replace values in an atomic vector.
#' 
#' @param x The atomic vector
#' @param na.0 The value to be replaced. Default is NaN.
#' @param na.1 The replacement. Default is NA.
#' @family generalUtils
#' @export
#' @examples
#' x <- sample(c(1:3,NaN), 20, replace=TRUE)
#' x 
#' replaceMissing(x)
replaceMissing <- function(x, na.0=NaN, na.1=NA) {
  if (is.nan(na.0)) x[is.nan(x)] <- na.1
  else if (is.na(na.0)) x[is.na(x)] <- na.1
  else x[is.na(x)] <- na.1
  x
}
